site:
  title: Islet
  url: https://nguyenhuythanh.com
  start_page: islet-site::index.adoc

content:
  sources:
    - url: https://github.com/thanhnguyen2187/islet-site.git

ui:
  bundle:
    url: https://github.com/bonitasoft/bonita-documentation-site/raw/master/resources/antora-ui-bundle.zip
