version: "3.7"

services:

  islet-site:
    container_name: islet_site
    restart: always
    ports: ["80:80", "443:443"]
    image: caddy:2.4.0-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./site/public:/var/www/public

  islet-fathom:
    container_name: islet_analytics
    image: usefathom/fathom:latest
    env_file: .env
    volumes:
      - ./fathom.db:/app/fathom.db
