name: Build & Deploy

on:
  push:
   branches: [master]

permissions:
  contents: write

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      working-directory: ./site
      run: hugo --minify

    - name: Deploy
      working-directory: ./site
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public

