name: Build & Deploy

on:
  push:
   branches: [master]

permissions:
  contents: write

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3'
        extended: true

    - name: Update config.toml
      working-directory: ./site
      run: |
        sed -i 's/nguyenhuythanh.com/thanhnguyen2187.github.io\/islet/g' config.toml

    - name: Build
      working-directory: ./site
      run: |
        hugo \
          --minify \
          --baseURL https://thanhnguyen2187.github.io/islet/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./site/public

